In [1]:
# from google.colab import files
# files.upload()

In [2]:
import pandas as pd
import numpy as np

In [3]:
data_preprocessed = pd.read_csv('Final_Absenteeism_preprocessed.csv')
data_preprocessed.head()

Reason1  Reason2  Reason3  Reason4  Month  Day of the Week  \
0        0        0        0        1      7                5   
1        0        0        0        0      7                5   
2        0        0        0        1      7                6   
3        1        0        0        0      7                0   
4        0        0        0        1      7                0   

   Transportation Expense  Distance to Work  Age  \
0                     289                36   33   
1                     118                13   50   
2                     179                51   38   
3                     279                 5   39   
4                     289                36   33   

   Daily Work Load Average(in Minutes)  Body Mass Index  Education  Children  \
0                              239.554               30          0         2   
1                              239.554               31          0         1   
2                              239.554               31          0         0   
3                              239.554               24          0         2   
4                              239.554               30          0         2   

   Pets  Absenteeism Time in Hours  
0     1                          4  
1     0                          0  
2     0                          2  
3     0                          4  
4     1                          2

In [4]:
data_median = data_preprocessed['Absenteeism Time in Hours'].median()
data_median

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>3, 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason1  Reason2  Reason3  Reason4  Month  Day of the Week  \
0        0        0        0        1      7                5   
1        0        0        0        0      7                5   
2        0        0        0        1      7                6   
3        1        0        0        0      7                0   
4        0        0        0        1      7                0   

   Transportation Expense  Distance to Work  Age  \
0                     289                36   33   
1                     118                13   50   
2                     179                51   38   
3                     279                 5   39   
4                     289                36   33   

   Daily Work Load Average(in Minutes)  Body Mass Index  Education  Children  \
0                              239.554               30          0         2   
1                              239.554               31          0         1   
2                              239.554               31          0         0   
3                              239.554               24          0         2   
4                              239.554               30          0         2   

   Pets  Absenteeism Time in Hours  Excessive Absenteeism  
0     1                          4                      1  
1     0                          0                      0  
2     0                          2                      0  
3     0                          4                      1  
4     1                          2                      0

In [7]:
targets.sum()/targets.shape[0]

np.float64(0.45571428571428574)

We devied targets in 2 categories, for absenteeism less than median the target is 0, otherwise it's 1 => The target column is balanced

**Backward Elimination**
*The idea is that we can simplify our model by removing all features which have close to no contribution to the model.*
=> We will remove the variables that have very small weight; consist of 'Day of the Week', 'Distance to Work', 'Daily Work Load Average(in Minutes)'



In [8]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Distance to Work',
                                            'Daily Work Load Average(in Minutes)','Day of the Week'], axis=1)
data_with_targets.head()

Reason1  Reason2  Reason3  Reason4  Month  Transportation Expense  Age  \
0        0        0        0        1      7                     289   33   
1        0        0        0        0      7                     118   50   
2        0        0        0        1      7                     179   38   
3        1        0        0        0      7                     279   39   
4        0        0        0        1      7                     289   33   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

In [9]:
feature_size = data_with_targets.shape[1]
unscaled_inputs = data_with_targets.iloc[:,:(feature_size-1)]
unscaled_inputs.head()

Reason1  Reason2  Reason3  Reason4  Month  Transportation Expense  Age  \
0        0        0        0        1      7                     289   33   
1        0        0        0        0      7                     118   50   
2        0        0        0        1      7                     179   38   
3        1        0        0        0      7                     279   39   
4        0        0        0        1      7                     289   33   

   Body Mass Index  Education  Children  Pets  
0               30          0         2     1  
1               31          0         1     0  
2               31          0         0     0  
3               24          0         2     0  
4               30          0         2     1

Standardization

In [10]:
from sklearn.preprocessing import StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin

In [11]:
class CustomScaler(BaseEstimator, TransformerMixin):

  def __init__(self, columns):
    self.scaler = StandardScaler()
    self.columns = columns
    self.mean = None
    self.var = None

  def fit(self, X, y=None):
    self.scaler.fit(X[self.columns], y)
    self.mean = np.mean(X[self.columns])
    self.var = np.var(X[self.columns])
    return self

  def transform(self, X, y=None, copy=None):
    init_col_order = X.columns
    X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]),
                            columns=self.columns)
    X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
    return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]


In [12]:
unscaled_inputs.columns.values

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [13]:
columns_to_omit = ['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Education']
columns_to_scale = [x for x in unscaled_inputs.columns.values
                    if x not in columns_to_omit]
columns_to_scale

['Month',
 'Transportation Expense',
 'Age',
 'Body Mass Index',
 'Children',
 'Pets']

In [14]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [15]:
absenteeism_scaler.fit(unscaled_inputs)

/usr/local/lib/python3.11/dist-packages/numpy/_core/fromnumeric.py:4006: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


CustomScaler(columns=['Month', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [16]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs.shape

(700, 11)

Split the dataset into train and test

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, test_size=0.2, random_state=14)

Using Logistic Regression

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
reg = LogisticRegression()
reg.fit(x_train, y_train)
reg.score(x_train, y_train)

0.7875

Calculating the model accuracy manually

In [21]:
model_output = reg.predict(x_train)

In [22]:
true_predict = np.sum(model_output == y_train)

In [23]:
num_of_samples = model_output.shape[0]

In [24]:
true_predict_ratio = true_predict / num_of_samples
true_predict_ratio

np.float64(0.7875)

Creating the Summary Table

In [25]:
reg.intercept_

array([-1.51928764])

In [26]:
reg.coef_

array([[ 2.69541044,  0.94732548,  3.30525694,  0.54540993,  0.16143338,
         0.57916598, -0.26407758,  0.23015765, -0.20730456,  0.36083343,
        -0.47890791]])

In [27]:
feature_name = unscaled_inputs.columns.values
feature_name

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [28]:
summary_table = pd.DataFrame(columns=['Feature Name'], data=feature_name)

In [29]:
summary_table['Coefficient'] = np.transpose(reg.coef_)

In [30]:
summary_table.index = summary_table.index + 1

In [31]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Name  Coefficient
0                Intercept    -1.519288
1                  Reason1     2.695410
2                  Reason2     0.947325
3                  Reason3     3.305257
4                  Reason4     0.545410
5                    Month     0.161433
6   Transportation Expense     0.579166
7                      Age    -0.264078
8          Body Mass Index     0.230158
9                Education    -0.207305
10                Children     0.360833
11                    Pets    -0.478908

In [32]:
summary_table['Odds Ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature Name  Coefficient  Odds Ratio
0                Intercept    -1.519288    0.218868
1                  Reason1     2.695410   14.811597
2                  Reason2     0.947325    2.578803
3                  Reason3     3.305257   27.255544
4                  Reason4     0.545410    1.725316
5                    Month     0.161433    1.175194
6   Transportation Expense     0.579166    1.784549
7                      Age    -0.264078    0.767914
8          Body Mass Index     0.230158    1.258798
9                Education    -0.207305    0.812772
10                Children     0.360833    1.434524
11                    Pets    -0.478908    0.619460

In [44]:
summary_table = summary_table.sort_values('Odds Ratio', ascending=False)
summary_table

Feature Name  Coefficient  Odds Ratio
3                  Reason3     3.305257   27.255544
1                  Reason1     2.695410   14.811597
2                  Reason2     0.947325    2.578803
6   Transportation Expense     0.579166    1.784549
4                  Reason4     0.545410    1.725316
10                Children     0.360833    1.434524
8          Body Mass Index     0.230158    1.258798
5                    Month     0.161433    1.175194
9                Education    -0.207305    0.812772
7                      Age    -0.264078    0.767914
11                    Pets    -0.478908    0.619460
0                Intercept    -1.519288    0.218868

Creating a Module

In [34]:
import pickle

In [35]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [36]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)