In [1]:
# from google.colab import files
# files.upload()

In [2]:
import pandas as pd
import numpy as np

In [3]:
data_preprocessed = pd.read_csv('Final_Absenteeism_preprocessed.csv')
data_preprocessed.head()

Reason1  Reason2  Reason3  Reason4  Month  Day of the Week  \
0        0        0        0        1      7                5   
1        0        0        0        0      7                5   
2        0        0        0        1      7                6   
3        1        0        0        0      7                0   
4        0        0        0        1      7                0   

   Transportation Expense  Distance to Work  Age  \
0                     289                36   33   
1                     118                13   50   
2                     179                51   38   
3                     279                 5   39   
4                     289                36   33   

   Daily Work Load Average(in Minutes)  Body Mass Index  Education  Children  \
0                              239.554               30          0         2   
1                              239.554               31          0         1   
2                              239.554               31          0         0   
3                              239.554               24          0         2   
4                              239.554               30          0         2   

   Pets  Absenteeism Time in Hours  
0     1                          4  
1     0                          0  
2     0                          2  
3     0                          4  
4     1                          2

In [4]:
data_median = data_preprocessed['Absenteeism Time in Hours'].median()
data_median

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>3, 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason1  Reason2  Reason3  Reason4  Month  Day of the Week  \
0        0        0        0        1      7                5   
1        0        0        0        0      7                5   
2        0        0        0        1      7                6   
3        1        0        0        0      7                0   
4        0        0        0        1      7                0   

   Transportation Expense  Distance to Work  Age  \
0                     289                36   33   
1                     118                13   50   
2                     179                51   38   
3                     279                 5   39   
4                     289                36   33   

   Daily Work Load Average(in Minutes)  Body Mass Index  Education  Children  \
0                              239.554               30          0         2   
1                              239.554               31          0         1   
2                              239.554               31          0         0   
3                              239.554               24          0         2   
4                              239.554               30          0         2   

   Pets  Absenteeism Time in Hours  Excessive Absenteeism  
0     1                          4                      1  
1     0                          0                      0  
2     0                          2                      0  
3     0                          4                      1  
4     1                          2                      0

In [7]:
targets.sum()/targets.shape[0]

np.float64(0.45571428571428574)

We devied targets in 2 categories, for absenteeism less than median the target is 0, otherwise it's 1 => The target column is balanced

In [8]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis=1)
data_with_targets.head()

Reason1  Reason2  Reason3  Reason4  Month  Day of the Week  \
0        0        0        0        1      7                5   
1        0        0        0        0      7                5   
2        0        0        0        1      7                6   
3        1        0        0        0      7                0   
4        0        0        0        1      7                0   

   Transportation Expense  Distance to Work  Age  \
0                     289                36   33   
1                     118                13   50   
2                     179                51   38   
3                     279                 5   39   
4                     289                36   33   

   Daily Work Load Average(in Minutes)  Body Mass Index  Education  Children  \
0                              239.554               30          0         2   
1                              239.554               31          0         1   
2                              239.554               31          0         0   
3                              239.554               24          0         2   
4                              239.554               30          0         2   

   Pets  Excessive Absenteeism  
0     1                      1  
1     0                      0  
2     0                      0  
3     0                      1  
4     1                      0

In [9]:
feature_size = data_with_targets.shape[1]
unscaled_inputs = data_with_targets.iloc[:,:(feature_size-1)]
unscaled_inputs.head()

Reason1  Reason2  Reason3  Reason4  Month  Day of the Week  \
0        0        0        0        1      7                5   
1        0        0        0        0      7                5   
2        0        0        0        1      7                6   
3        1        0        0        0      7                0   
4        0        0        0        1      7                0   

   Transportation Expense  Distance to Work  Age  \
0                     289                36   33   
1                     118                13   50   
2                     179                51   38   
3                     279                 5   39   
4                     289                36   33   

   Daily Work Load Average(in Minutes)  Body Mass Index  Education  Children  \
0                              239.554               30          0         2   
1                              239.554               31          0         1   
2                              239.554               31          0         0   
3                              239.554               24          0         2   
4                              239.554               30          0         2   

   Pets  
0     1  
1     0  
2     0  
3     0  
4     1

Standardization

In [10]:
from sklearn.preprocessing import StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin

In [11]:
class CustomScaler(BaseEstimator, TransformerMixin):

  def __init__(self, columns):
    self.scaler = StandardScaler()
    self.columns = columns
    self.mean = None
    self.var = None

  def fit(self, X, y=None):
    self.scaler.fit(X[self.columns], y)
    self.mean = np.mean(X[self.columns])
    self.var = np.var(X[self.columns])
    return self

  def transform(self, X, y=None, copy=None):
    init_col_order = X.columns
    X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]),
                            columns=self.columns)
    X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
    return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]


In [12]:
unscaled_inputs.columns.values

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average(in Minutes)', 'Body Mass Index',
       'Education', 'Children', 'Pets'], dtype=object)

In [13]:
columns_to_scale = ['Month', 'Day of the Week', 'Transportation Expense',
                    'Distance to Work','Age', 'Daily Work Load Average(in Minutes)',
                    'Body Mass Index', 'Children', 'Pets']

In [14]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [15]:
absenteeism_scaler.fit(unscaled_inputs)

/usr/local/lib/python3.11/dist-packages/numpy/_core/fromnumeric.py:4006: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


CustomScaler(columns=['Month', 'Day of the Week', 'Transportation Expense',
                      'Distance to Work', 'Age',
                      'Daily Work Load Average(in Minutes)', 'Body Mass Index',
                      'Children', 'Pets'])

In [16]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs.shape

(700, 14)

Split the dataset into train and test

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, test_size=0.2, random_state=14)

Using Logistic Regression

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
reg = LogisticRegression()
reg.fit(x_train, y_train)
reg.score(x_train, y_train)

0.7928571428571428

Calculating the model accuracy manually

In [21]:
model_output = reg.predict(x_train)

In [22]:
true_predict = np.sum(model_output == y_train)

In [23]:
num_of_samples = model_output.shape[0]

In [24]:
true_predict_ratio = true_predict / num_of_samples
true_predict_ratio

np.float64(0.7928571428571428)

Creating the Summary Table

In [25]:
reg.intercept_

array([-1.54950026])

In [26]:
reg.coef_

array([[ 2.71716709,  0.95980038,  3.33025511,  0.59707107,  0.16089457,
         0.07443094,  0.59909325, -0.06967482, -0.27890899,  0.0099309 ,
         0.23498605, -0.2459835 ,  0.36329697, -0.48139648]])

In [27]:
feature_name = unscaled_inputs.columns.values
feature_name

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average(in Minutes)', 'Body Mass Index',
       'Education', 'Children', 'Pets'], dtype=object)

In [28]:
summary_table = pd.DataFrame(columns=['Feature Name'], data=feature_name)

In [29]:
summary_table['Coefficient'] = np.transpose(reg.coef_)

In [30]:
summary_table.index = summary_table.index + 1
type(summary_table)

pandas.core.frame.DataFrame

In [31]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
# summary_table = summary_table.sort_index()
type(summary_table)

pandas.core.frame.DataFrame

In [32]:
summary_table['Odds Ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature Name  Coefficient  Odds Ratio
1                               Reason1     2.717167   15.137379
2                               Reason2     0.959800    2.611175
3                               Reason3     3.330255   27.945470
4                               Reason4     0.597071    1.816790
5                                 Month     0.160895    1.174561
6                       Day of the Week     0.074431    1.077271
7                Transportation Expense     0.599093    1.820467
8                      Distance to Work    -0.069675    0.932697
9                                   Age    -0.278909    0.756609
10  Daily Work Load Average(in Minutes)     0.009931    1.009980
11                      Body Mass Index     0.234986    1.264891
12                            Education    -0.245983    0.781935
13                             Children     0.363297    1.438063
14                                 Pets    -0.481396    0.617920
0                             Intercept    -1.549500    0.212354

In [33]:
summary_table.sort_values('Odds Ratio', ascending=False)
summary_table

Feature Name  Coefficient  Odds Ratio
1                               Reason1     2.717167   15.137379
2                               Reason2     0.959800    2.611175
3                               Reason3     3.330255   27.945470
4                               Reason4     0.597071    1.816790
5                                 Month     0.160895    1.174561
6                       Day of the Week     0.074431    1.077271
7                Transportation Expense     0.599093    1.820467
8                      Distance to Work    -0.069675    0.932697
9                                   Age    -0.278909    0.756609
10  Daily Work Load Average(in Minutes)     0.009931    1.009980
11                      Body Mass Index     0.234986    1.264891
12                            Education    -0.245983    0.781935
13                             Children     0.363297    1.438063
14                                 Pets    -0.481396    0.617920
0                             Intercept    -1.549500    0.212354

**Backward Elimination**
*The idea is that we can simplify our model by removing all features which have close to no contribution to the model.*
=> We will remove the variables that have very small weight; consist of 'Day of the Week', 'Distance to Work', 'Daily Work Load Average(in Minutes)'



Creating a Module

In [34]:
import pickle

In [35]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [36]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)