In [3]:
import pandas as pd
import numpy as np

In [4]:
data_preprocessed = pd.read_csv('Final_Absenteeism_preprocessed.csv')
data_preprocessed.head()

Reason1  Reason2  Reason3  Reason4  Month  Day of the Week  \
0        0        0        0        1      7                5   
1        0        0        0        0      7                5   
2        0        0        0        1      7                6   
3        1        0        0        0      7                0   
4        0        0        0        1      7                0   

   Transportation Expense  Distance to Work  Age  \
0                     289                36   33   
1                     118                13   50   
2                     179                51   38   
3                     279                 5   39   
4                     289                36   33   

   Daily Work Load Average(in Minutes)  Body Mass Index  Education  Children  \
0                              239.554               30          0         2   
1                              239.554               31          0         1   
2                              239.554               31          0         0   
3                              239.554               24          0         2   
4                              239.554               30          0         2   

   Pets  Absenteeism Time in Hours  
0     1                          4  
1     0                          0  
2     0                          2  
3     0                          4  
4     1                          2

In [5]:
data_median = data_preprocessed['Absenteeism Time in Hours'].median()
data_median

3.0

In [6]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>3, 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason1  Reason2  Reason3  Reason4  Month  Day of the Week  \
0        0        0        0        1      7                5   
1        0        0        0        0      7                5   
2        0        0        0        1      7                6   
3        1        0        0        0      7                0   
4        0        0        0        1      7                0   

   Transportation Expense  Distance to Work  Age  \
0                     289                36   33   
1                     118                13   50   
2                     179                51   38   
3                     279                 5   39   
4                     289                36   33   

   Daily Work Load Average(in Minutes)  Body Mass Index  Education  Children  \
0                              239.554               30          0         2   
1                              239.554               31          0         1   
2                              239.554               31          0         0   
3                              239.554               24          0         2   
4                              239.554               30          0         2   

   Pets  Absenteeism Time in Hours  Excessive Absenteeism  
0     1                          4                      1  
1     0                          0                      0  
2     0                          2                      0  
3     0                          4                      1  
4     1                          2                      0

In [8]:
targets.sum()/targets.shape[0]

0.45571428571428574

We devied targets in 2 categories, for absenteeism less than median the target is 0, otherwise it's 1 => The target column is balanced

In [9]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis=1)
data_with_targets.head()

Reason1  Reason2  Reason3  Reason4  Month  Day of the Week  \
0        0        0        0        1      7                5   
1        0        0        0        0      7                5   
2        0        0        0        1      7                6   
3        1        0        0        0      7                0   
4        0        0        0        1      7                0   

   Transportation Expense  Distance to Work  Age  \
0                     289                36   33   
1                     118                13   50   
2                     179                51   38   
3                     279                 5   39   
4                     289                36   33   

   Daily Work Load Average(in Minutes)  Body Mass Index  Education  Children  \
0                              239.554               30          0         2   
1                              239.554               31          0         1   
2                              239.554               31          0         0   
3                              239.554               24          0         2   
4                              239.554               30          0         2   

   Pets  Excessive Absenteeism  
0     1                      1  
1     0                      0  
2     0                      0  
3     0                      1  
4     1                      0

In [10]:
feature_size = data_with_targets.shape[1]
unscaled_inputs = data_with_targets.iloc[:,:(feature_size-1)]
unscaled_inputs.head()

Reason1  Reason2  Reason3  Reason4  Month  Day of the Week  \
0        0        0        0        1      7                5   
1        0        0        0        0      7                5   
2        0        0        0        1      7                6   
3        1        0        0        0      7                0   
4        0        0        0        1      7                0   

   Transportation Expense  Distance to Work  Age  \
0                     289                36   33   
1                     118                13   50   
2                     179                51   38   
3                     279                 5   39   
4                     289                36   33   

   Daily Work Load Average(in Minutes)  Body Mass Index  Education  Children  \
0                              239.554               30          0         2   
1                              239.554               31          0         1   
2                              239.554               31          0         0   
3                              239.554               24          0         2   
4                              239.554               30          0         2   

   Pets  
0     1  
1     0  
2     0  
3     0  
4     1

Standardization

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
absenteeism_scaler = StandardScaler().fit(unscaled_inputs)

In [13]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs.shape

(700, 14)

Split the dataset into train and test

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, test_size=0.2, random_state=14)

Using Logistic Regression 

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
reg = LogisticRegression()
reg.fit(x_train, y_train)
reg.score(x_train, y_train)

0.8017857142857143

Calculating the model accuracy manually

In [18]:
model_output = reg.predict(x_train)

In [19]:
true_predict = np.sum(model_output == y_train)

In [20]:
num_of_samples = model_output.shape[0]

In [21]:
true_predict_ratio = true_predict / num_of_samples
true_predict_ratio

0.8017857142857143

Creating the Summary Table

In [22]:
reg.intercept_

array([-0.14509308])

In [23]:
reg.coef_

array([[ 2.00608314,  0.34037161,  1.89582039,  1.18874418,  0.19539272,
         0.08775858,  0.69683118, -0.10148497, -0.32345418,  0.0227231 ,
         0.29513137, -0.13168926,  0.37604943, -0.57282287]])

In [24]:
feature_name = unscaled_inputs.columns.values
feature_name

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average(in Minutes)', 'Body Mass Index',
       'Education', 'Children', 'Pets'], dtype=object)

In [25]:
summary_table = pd.DataFrame(columns=['Feature Name'], data=feature_name)

In [26]:
summary_table['Coefficient'] = np.transpose(reg.coef_)

In [27]:
summary_table.index = summary_table.index + 1
type(summary_table)

pandas.core.frame.DataFrame

In [28]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
# summary_table = summary_table.sort_index()
type(summary_table)

pandas.core.frame.DataFrame

In [29]:
summary_table['Odds Ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature Name  Coefficient  Odds Ratio
1                               Reason1     2.006083    7.434142
2                               Reason2     0.340372    1.405470
3                               Reason3     1.895820    6.658008
4                               Reason4     1.188744    3.282956
5                                 Month     0.195393    1.215788
6                       Day of the Week     0.087759    1.091725
7                Transportation Expense     0.696831    2.007382
8                      Distance to Work    -0.101485    0.903495
9                                   Age    -0.323454    0.723645
10  Daily Work Load Average(in Minutes)     0.022723    1.022983
11                      Body Mass Index     0.295131    1.343303
12                            Education    -0.131689    0.876613
13                             Children     0.376049    1.456519
14                                 Pets    -0.572823    0.563931
0                             Intercept    -0.145093    0.864942

In [30]:
summary_table.sort_values('Odds Ratio', ascending=False)
summary_table

Feature Name  Coefficient  Odds Ratio
1                               Reason1     2.006083    7.434142
2                               Reason2     0.340372    1.405470
3                               Reason3     1.895820    6.658008
4                               Reason4     1.188744    3.282956
5                                 Month     0.195393    1.215788
6                       Day of the Week     0.087759    1.091725
7                Transportation Expense     0.696831    2.007382
8                      Distance to Work    -0.101485    0.903495
9                                   Age    -0.323454    0.723645
10  Daily Work Load Average(in Minutes)     0.022723    1.022983
11                      Body Mass Index     0.295131    1.343303
12                            Education    -0.131689    0.876613
13                             Children     0.376049    1.456519
14                                 Pets    -0.572823    0.563931
0                             Intercept    -0.145093    0.864942

Creating a Module

In [33]:
import pickle

In [34]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [35]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)